# Generated by Django 5.2.14 on 2026-06-04 05:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Физический адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Геопозиция (координаты)')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пункт приема',
                'verbose_name_plural': 'Пункты приема',
            },
        ),
        migrations.CreateModel(
            name='RecyclerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании переработчика')),
                ('license_number', models.CharField(max_length=100, verbose_name='Номер лицензии на утилизацию')),
            ],
            options={
                'verbose_name': 'Компания-переработчик',
                'verbose_name_plural': 'Компании-переработчики',
            },
        ),
    ]
