# Generated by Django 5.2.14 on 2026-06-04 06:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании переработчика')),
                ('license_number', models.CharField(max_length=100, verbose_name='Номер лицензии на утилизацию')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания-переработчик',
                'verbose_name_plural': 'Компании-переработчики',
            },
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пункта приёма')),
                ('address', models.CharField(max_length=255, verbose_name='Физический адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Геопозиция (координаты)')),
                ('working_hours', models.JSONField(default=dict, help_text='Пример: {"mon-fri": "09:00-18:00", "sat": "10:00-15:00", "sun": "closed"}', verbose_name='Часы работы')),
                ('accepted_categories', models.JSONField(default=list, help_text='Пример: ["laptop", "phone", "tablet"]', verbose_name='Принимаемые категории устройств')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Сертифицирован')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='recyclers.recyclercompany', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Пункт приёма',
                'verbose_name_plural': 'Пункты приёма',
            },
        ),
        migrations.CreateModel(
            name='RecyclingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приёмки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='recyclers.collectionpoint', verbose_name='Пункт приёма')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_records', to='devices.deviceunit', verbose_name='Экземпляр устройства')),
            ],
            options={
                'verbose_name': 'Запись об утилизации',
                'verbose_name_plural': 'Записи об утилизации',
            },
        ),
    ]
