# Generated by Django 5.2.14 on 2026-06-04 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recyclers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='recyclers.recyclercompany', verbose_name='Компания'),
        ),
    ]
