# Generated by Django 5.2.14 on 2026-06-04 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('category', models.CharField(max_length=100, verbose_name='Категория устройства')),
                ('release_date', models.DateField(verbose_name='Дата выпуска модели')),
                ('material_composition', models.JSONField(help_text='Пластик, металлы, батареи, опасные вещества.', verbose_name='Состав материалов (WEEE data)')),
                ('eco_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Экологический индекс (0-100)')),
                ('manual_url', models.URLField(blank=True, null=True, verbose_name='PDF-инструкция по разборке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='manufacturers.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель устройства',
                'verbose_name_plural': 'Модели устройств',
            },
        ),
        migrations.CreateModel(
            name='DeviceUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('manufactured_at', models.DateField(blank=True, null=True, verbose_name='Дата производства')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='devices.devicemodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Экземпляр устройства',
                'verbose_name_plural': 'Экземпляры устройств',
                'unique_together': {('device_model', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='DevicePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRODUCED', 'ПРОИЗВЕДЕНО'), ('IN_USE', 'В ИСПОЛЬЗОВАНИИ'), ('PLANNED', 'ЗАПЛАНИРОВАНО'), ('COLLECTED', 'СОБРАНО В ПУНКТЕ ПРИЕМА'), ('RECYCLED', 'УТИЛИЗИРОВАНО/ПЕРЕРАБОТАНО')], default='PRODUCED', max_length=20, verbose_name='Статус жизненного цикла')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_devices', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='devices.deviceunit', verbose_name='Экземпляр устройства')),
            ],
            options={
                'verbose_name': 'Паспорт устройства',
                'verbose_name_plural': 'Паспорта устройств',
            },
        ),
    ]
