# Generated by Django 5.2.14 on 2026-06-04 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назначение партии/модели (Например ProBook X15)')),
                ('release_date', models.DateField(verbose_name='Дата выпуска партии')),
                ('components_spec', models.JSONField(help_text='Данные о содержании пластика, металлов, батарей и опасных веществ.', verbose_name='Спецификация материалов и компонентов (WEEE data)')),
                ('manual_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на PDF-инструкцию по разборке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Партия устройств',
                'verbose_name_plural': 'Партий устройств',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер производителя')),
                ('status', models.CharField(choices=[('PRODUCED', 'ПРОИЗВЕДЕНО'), ('IN_USE', 'В ИСПОЛЬЗОВАНИИ'), ('PLANNED', 'ЗАПЛАНИРОВАНО'), ('COLLECTED', 'СОБРАНО В ПУНКТЕ ПРИЕМА'), ('RECYCLED', 'УТИЛИЗИРОВАНО/ПЕРЕРАБОТАНО')], default='PRODUCED', max_length=20, verbose_name='Статус жизненного цикла')),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Устройства (Цифровой паспорт)',
                'verbose_name_plural': 'Устройства (Цифровые паспорта)',
            },
        ),
    ]
