# Generated by Django 5.2.14 on 2026-06-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='manufacturers.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='device',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.batch', verbose_name='Партия'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('batch', 'serial_number')},
        ),
    ]
