# Generated by Django 5.2.14 on 2026-06-04 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('country', models.CharField(max_length=100, verbose_name='Страна регистрации')),
                ('website', models.URLField(max_length=255, verbose_name='Веб-сайт')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='API ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weee_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='WEEE-регистрационный номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-Владелец')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
