# Generated by Django 5.2.14 on 2026-06-04 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('country', models.CharField(max_length=100, verbose_name='Страна регистрации')),
                ('website', models.CharField(max_length=255, verbose_name='Веб-сайт')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='API ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
